# Generated by Django 5.1.5 on 2025-05-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
