# Generated by Django 5.1.5 on 2025-11-06 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatments",
            name="half_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=55.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="treatments",
            name="one_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=80.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="treatments",
            name="two_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=110.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
